# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-h9BFNNeiUagnQBcLcP3jhFpcUMW0rlN
"""

import streamlit as st
import pandas as pd
import joblib

# Load model and scaler
model = joblib.load('cheating_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("🕵️ Online Exam Cheating Detection")

# Input form
st.header("Student Session Info")
tab_switch = st.slider("Tab Switch Count", 0, 20, 2)
time_taken = st.slider("Time Taken (seconds)", 60, 600, 300)
answer_changes = st.slider("Answer Changes", 0, 10, 1)
ip_changes = st.selectbox("IP Changed?", [0, 1])
copy_paste = st.slider("Copy-Paste Count", 0, 20, 1)
apps_open = st.selectbox("Suspicious Apps Opened?", [0, 1])

# Predict
if st.button("Detect Cheating"):
    features = pd.DataFrame([[tab_switch, time_taken, answer_changes, ip_changes, copy_paste, apps_open]],
                            columns=["tab_switch_count", "time_taken_sec", "answer_changes", "ip_changes",
                                     "copy_paste_count", "suspicious_apps_open"])
    scaled = scaler.transform(features)
    prediction = model.predict(scaled)[0]
    prob = model.predict_proba(scaled)[0][1]

    if prediction == 1:
        st.error(f"⚠️ Cheating Detected! (Confidence: {prob:.2%})")
    else:
        st.success(f"✅ No Cheating Detected (Confidence: {1 - prob:.2%})")

