# -*- coding: utf-8 -*-
"""chatbot.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVAYwmIHO756M2pp_W6V_plUB_7_b3wS
"""

import streamlit as st
import joblib
import pandas as pd

model = joblib.load('cheating_model.pkl')
scaler = joblib.load('scaler.pkl')

st.title("🤖 CheatBot: Exam Session Assistant")

query = st.text_input("Ask me something like: 'Student switched tabs 8 times, spent 200 seconds, changed answers 2 times...'")

if st.button("Predict from Query") and query:
    import re
    numbers = list(map(int, re.findall(r'\d+', query)))
    if len(numbers) >= 6:
        features = pd.DataFrame([numbers[:6]], columns=["tab_switch_count", "time_taken_sec", "answer_changes",
                                                        "ip_changes", "copy_paste_count", "suspicious_apps_open"])
        scaled = scaler.transform(features)
        pred = model.predict(scaled)[0]
        prob = model.predict_proba(scaled)[0][1]
        st.write("🧠 Prediction:", "Cheating" if pred else "Not Cheating")
        st.write(f"Confidence: {prob:.2%}")
    else:
        st.warning("⚠️ Please provide at least 6 numerical indicators in your query.")

!pip install streamlit